### ISSUE TITLE
This repo is a copy of PMZSwitch

### ISSUE THREAD

**Issue by kovpas** [knn90/Switcher#2]
Original repository is here: https://github.com/kovpas/PMZSwitch

Please remove this code, and leave a link to the original code.

**Comment by kovpas** [comment]
I was mislead by the animation, which looks very similar to the one in my repo. Other than that this repo is not a copy.

Anyway, I think, it would be nice to see credits to @andmironov for original animation.

**Comment by knn90** [comment]
@kovpas I implemented several months ago. The idea come from here http://uimovement.com/ui/654/yet-another-toggle-animation. May be you too. Thank you

**Comment by kovpas** [comment]
@knn90 yep, source is the same, implementation is different.
