### ISSUE TITLE
bool type change switcher state

### ISSUE THREAD

**Issue by HideCode7** [knn90/Switcher#4]
If you want to give a bool initial value and the switcher already start in this state how can I do ? 
example open the viewcontroller and say I want the switcher to true and it come true .

**Comment by knn90** [comment]
You can use didset block to call animationSwitcherButton() whenever status property is set

**Comment by HideCode7** [comment]
Can you give an example of how to make that call? thank you. By the way, good Switcher :)

**Comment by knn90** [comment]
Sorry, may be it's too late now but still better than never :)

I added new function to init with default value. 

Thank you

**Comment by hartjosh** [comment]
How do you set the initial value programmatically?  I try switcher.on = true and it resets it to false.  In storyboards I have the value set to default.
