### ISSUE TITLE
Question: iOS 8 compatibility 

### ISSUE THREAD

**Issue by oferRounds** [knn90/Switcher#9]
Hi @knn90 

First of all – thanks for this awesome library!

I wanted to ask: I see the minimum deployment target is 9.3. May I ask for the reason for it, or what I can change to have it also support iOS 8?

Thanks!
Ofer

**Comment by knn90** [comment]
Hi @oferRounds 

It's actually compatible with iOS 8.0 and later. Let me update pod spec. 

Thank you for making issue 👍

**Comment by oferRounds** [comment]
Yay! But I actually think it’s iOS 9.0+, as I see, for example, that you use: `centerYAnchor`

**Comment by knn90** [comment]
Oh yes, I think Anchor Layout only available since iOS 9. So how can I help you ?

**Comment by oferRounds** [comment]
So, I think — unless I’m missing something — that the minimum should be iOS 9.0 (instead of 9.3)

**Comment by knn90** [comment]
Ok let me update podspec. Thank you

**Comment by oferRounds** [comment]
Thank YOU

**Comment by knn90** [comment]
Sorry because it takes time. New version available with deployment target iOS 9.0
